### ISSUE TITLE
Card [Design]

### ISSUE THREAD

**Issue by nathanacurtis** [EightShapes/esds-library#67]
Propose: https://github.com/EightShapes/esds-library/issues/59

**Comment by jamesmelzer** [comment]
MUST HAVE

- [ ] additional card block class
- [ ] title (applies heading)
- [ ] description
- [ ] href / destination
- [ ] thumbnail (applies thumbnail): block (true/false; could fill with icon w/o URL) & URL
- [ ] microcopy/metadata/type
- [ ] content slot
- [ ] actions slot
- [ ] focus ring for toggling across cards
- [ ] hover alter content container background color
- [ ] hover enlarge thumbnail, triggered if hovering card (not just thumbnail?)

SHOULD HAVE

isolated tests

- [ ] design system articles, thumbnails
- [ ] case studies, thumbnails
- [ ] without thumbnail image, only thumbnail ...color or icon?

composition tests

- [ ] with button in actions slot
- [ ] with icons/button--icons in actions slot
- [ ] with random crap in content slot

**Comment by jamesmelzer** [comment]
First pass at card, across contexts. 

Open questions: 

* Need clarification on no-thumbnail expectations. Is this a missing image fallback, thus expecting perhaps a doc-type specific icon? I made a placeholder/icon style, much like we did for DiscEd's card. I kept it super neutral, like an error state, rather than their playful style. 
* Requirements call for a button, but what's our button style? All I could find was "huge orange button" and "huge ghost button". Both seem wrong for icon-only. What are our size steps? Anyway, I made placeholders for both. 

Feedback sought:

* Our current card focus ring is nearly invisible. It leverages hover state. I explored a different direction, with a clearer ring and an interactive blue title. 
* Our current hover state highlights the card background, but doesn't switch the title to interactive blue. I believe it should. Open question: only do it when there isn't a link in the actions slot? Is that logic too fussy?

![Card Context Exploration](https://user-images.githubusercontent.com/1207666/74497363-7bb42880-4eab-11ea-9e09-a5da149046d0.png)

**Comment by jamesmelzer** [comment]
First pass at card grid. You can copy a row to add a row. You can rearrange rows and cards. Does **not** manage card height. 

Row 2 left-most = current focus style
Row 2 right-most = proposed ALT focus style

![Card grid exploration](https://user-images.githubusercontent.com/1207666/74497918-ec0f7980-4eac-11ea-996e-0f971bb51721.png)

**Comment by jamesmelzer** [comment]
Proposed model for components with swappable parts: 

Options are collected into a frame that names the slot. (Note: Figma's display would benefit from _any_ visual hierarchy). 
![Screen Shot 2020-03-02 at 3 17 56 PM](https://user-images.githubusercontent.com/1207666/75714086-0ad98280-5c99-11ea-95b0-e641a8bd00be.png)

Alternate display, from Design System Organizer plugin:
"Default" is the actual card. There's only one variant. 
![Screen Shot 2020-03-02 at 3 20 46 PM](https://user-images.githubusercontent.com/1207666/75714272-69066580-5c99-11ea-8b6d-256a4a4bf417.png)
